import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Avatar } from '../components/Avatar';
import { ScreenHeader } from '../components/ScreenHeader';
import { theme } from '../styles/theme';
import { getSharedContent } from '../data/sharedContent';
import { MediaPreview } from '../components/MediaPreview';
import { FileRow } from '../components/FileRow';
import { EmptyState } from '../components/EmptyState';

export function ConversationDetailsScreen({ contact, conversation, onBack, onToggleMuted, onToggleArchived, children }) {
  const shared = getSharedContent(contact.id);
  return <View style={styles.screen}><ScreenHeader eyebrow="conversa" title="Detalhes" right={<Pressable accessibilityLabel="Voltar à conversa" accessibilityRole="button" onPress={onBack} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable>} /><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Avatar contact={contact} size={76} /><Text style={styles.name}>{contact.name}</Text><Text style={styles.detail}>{contact.online ? 'Disponível agora' : contact.detail}</Text></View><View style={styles.actions}><Pressable accessibilityLabel={conversation?.muted ? 'Ativar som da conversa' : 'Silenciar conversa'} accessibilityRole="button" accessibilityState={{ selected: Boolean(conversation?.muted) }} onPress={onToggleMuted} style={styles.action}><Text style={styles.actionIcon}>{conversation?.muted ? '◉' : '◎'}</Text><Text style={styles.actionText}>{conversation?.muted ? 'Ativar som' : 'Silenciar'}</Text></Pressable><Pressable accessibilityLabel={conversation?.archived ? 'Desarquivar conversa' : 'Arquivar conversa'} accessibilityRole="button" accessibilityState={{ selected: Boolean(conversation?.archived) }} onPress={onToggleArchived} style={styles.action}><Text style={styles.actionIcon}>⌑</Text><Text style={styles.actionText}>{conversation?.archived ? 'Desarquivar' : 'Arquivar'}</Text></Pressable></View><Text style={styles.sectionTitle}>Mídias</Text>{shared.media.length ? <View style={styles.media}>{shared.media.map((item) => <MediaPreview item={item} key={item.id} />)}</View> : <EmptyState title="Sem mídias" description="As imagens compartilhadas aparecerão aqui." />}<Text style={styles.sectionTitle}>Arquivos</Text>{shared.files.length ? <View style={styles.files}>{shared.files.map((item) => <FileRow item={item} key={item.id} />)}</View> : <EmptyState title="Sem arquivos" description="Os documentos compartilhados aparecerão aqui." />}{children}</ScrollView></View>;
}

const styles = StyleSheet.create({ screen: { backgroundColor: theme.colors.background, flex: 1 }, back: { alignItems: 'center', height: 44, justifyContent: 'center', width: 44 }, backText: { color: theme.colors.primary, fontSize: 36 }, content: { padding: theme.spacing.lg }, hero: { alignItems: 'center', backgroundColor: theme.colors.surface, borderRadius: theme.radius.lg, padding: theme.spacing.lg }, name: { color: theme.colors.ink, fontSize: 21, fontWeight: '900', marginTop: 12 }, detail: { color: theme.colors.muted, fontSize: 13, marginTop: 4 }, actions: { flexDirection: 'row', gap: 10, marginTop: 14 }, action: { alignItems: 'center', backgroundColor: theme.colors.primarySoft, borderRadius: theme.radius.md, flex: 1, minHeight: 80, padding: 12 }, actionIcon: { color: theme.colors.primary, fontSize: 23 }, actionText: { color: theme.colors.primary, fontSize: 13, fontWeight: '800', marginTop: 5 }, sectionTitle: { color: theme.colors.ink, fontSize: 16, fontWeight: '900', marginBottom: 10, marginTop: 22 }, media: { flexDirection: 'row', gap: 9 }, files: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.md, paddingHorizontal: 13 } });
