import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ScreenHeader } from './ScreenHeader';
import { theme } from '../styles/theme';

export function ConversationToolbar({ mode, onChangeMode, onOpenContacts, onOpenProfile }) {
  return <><ScreenHeader eyebrow="seu espaço" title="Círculo" right={<View style={styles.actions}><Pressable accessibilityLabel="Abrir perfil" accessibilityRole="button" onPress={onOpenProfile} style={styles.profile}><Text style={styles.profileText}>PO</Text></Pressable><Pressable accessibilityLabel="Abrir pessoas" accessibilityRole="button" onPress={onOpenContacts} style={styles.people}><Text style={styles.peopleIcon}>⌁</Text><Text style={styles.peopleText}>Pessoas</Text></Pressable></View>} /><Text style={styles.intro}>Conversas que fazem bem ao dia.</Text><View style={styles.filters}><Pressable accessibilityRole="button" accessibilityState={{ selected: mode === 'active' }} onPress={() => onChangeMode('active')} style={[styles.filter, mode === 'active' && styles.filterActive]}><Text style={[styles.filterText, mode === 'active' && styles.filterTextActive]}>Conversas</Text></Pressable><Pressable accessibilityRole="button" accessibilityState={{ selected: mode === 'archived' }} onPress={() => onChangeMode('archived')} style={[styles.filter, mode === 'archived' && styles.filterActive]}><Text style={[styles.filterText, mode === 'archived' && styles.filterTextActive]}>Arquivadas</Text></Pressable></View></>;
}

const styles = StyleSheet.create({ actions: { alignItems: 'center', flexDirection: 'row', gap: 8 }, profile: { alignItems: 'center', backgroundColor: theme.colors.sent, borderRadius: 22, height: 44, justifyContent: 'center', width: 44 }, profileText: { color: theme.colors.primary, fontSize: 12, fontWeight: '900' }, people: { alignItems: 'center', backgroundColor: theme.colors.primarySoft, borderRadius: theme.radius.pill, flexDirection: 'row', gap: 5, minHeight: 44, paddingHorizontal: 13, paddingVertical: 9 }, peopleIcon: { color: theme.colors.primary, fontSize: 20, fontWeight: '800' }, peopleText: { color: theme.colors.primary, fontSize: 12, fontWeight: '800' }, intro: { color: theme.colors.muted, fontSize: 15, marginHorizontal: theme.spacing.lg, marginTop: 7 }, filters: { flexDirection: 'row', gap: 8, marginHorizontal: theme.spacing.lg, marginTop: 18 }, filter: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.pill, justifyContent: 'center', minHeight: 44, paddingHorizontal: 14, paddingVertical: 8 }, filterActive: { backgroundColor: theme.colors.primary }, filterText: { color: theme.colors.muted, fontSize: 12, fontWeight: '800' }, filterTextActive: { color: '#FFFFFF' } });
